<?php

/**
 * Implements hook_theme()
 */
 function FormularioPlataformaYM_theme($existing, $type, $theme, $path) {
    return [
        'FormularioPlataformaYM' => [
            'variables' => [
                'content' => [
                    'header' => NULL,
                    'title' => NULL,
                    'lorem' => NULL,
                    'footer' => NULL,
                ]
            ]
        ],
        'request' => [
            'variables' => [
                'content' => [
                    'header' => NULL,
                    'title' => NULL,
                    'lorem' => NULL,
                    'footer' => NULL,
            ]
            ]
        ]
    ];
 }

function FormularioPlataformaYM_template($existing, $type, $theme, $path) {
    return [
        'FormularioPlataformaYM' => [
            'variables' => [
                'content' => [
                    'header' => NULL,
                    'title' => NULL,
                    'lorem' => NULL,
                    'footer' => NULL,
                ]
            ]
        ],
        'request' => [
            'variables' => [
                'content' => [
                    'header' => NULL,
                    'title' => NULL,
                    'lorem' => NULL,
                    'footer' => NULL,
            ]
            ]
        ],
        'template' => 'FormularioPlataformaYM',
    ];
}

?>